---
# tasks file for screen
- name: install
  apt:
    name: screen
    state: latest
  tags: [configuration, screen, screen-install]

- name: create configuration file
  template:
    src: etc/screenrc.j2
    dest: "{{ item }}/.screenrc"
    owner: root
    group: root
    mode: 0644
  with_items: screen_screenrc_destinations
  tags: [configuration, screen, screen-configuration]
